name: bindplane

on:
  pull_request:
  push:
    branches:
      - main

# Write back requires access to the repo
permissions:
  contents: write

# Run commits in order to prevent out of order write back commits.
concurrency:
  group: ${{ github.head_ref || github.ref_name }}
  cancel-in-progress: false

jobs:
  bindplane:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: observIQ/bindplane-op-action@main
        with:
          bindplane_remote_url: ${{ secrets.BINDPLANE_REMOTE_URL }}
          bindplane_api_key: ${{ secrets.BINDPLANE_API_KEY }}
          target_branch: main
          destination_path: destination/*.yaml
          configuration_path: configuration/*.yaml
          source_path: source/*.yaml
          processor_path: processor/*.yaml
          enable_otel_config_write_back: true
          configuration_output_dir: otel/
          token: ${{ secrets.GITHUB_TOKEN }}
          enable_auto_rollout: true
          configuration_output_branch: raw
